### PR TITLE
Show mainnet results first

### PR DESCRIPTION
**Pull request by andrewtoth**

### CODE REVIEW

**Comment by andrewtoth** [comment]
Didn't seem to work :/

**Comment by willcl-ark** [comment]
I think this _might_ work, but it's still, after much using GHA, unclear to me whether we run the workflow file from master/merge-base in PRs, or the modified one.

Going to merge this and find out.

If this does't work, I will investigate another method.

**Comment by andrewtoth** [comment]
It works :)

**Comment by willcl-ark** [comment]
It does!

**Pull request merged**
